### ISSUE TITLE
Crash on  Compute EFM via CNA with reversibility: off and only consider convex basis: on

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#211]
Project: SmallExample
Action: Compute Elementary Flux Modes/Vectors via CNA
check reversibility: off
only consider convex basis: on
```
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/efm_dialog.py", line 231, in compute
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 500, in eval
    plot_res=plot_res)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 382, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: questdlg is not available in this version of Octave
error: called from:
    questdlg at line 131, column 5
    conbasis_calc at line 244, column 16
    compute_elmodes at line 247, column 100
    CNAcomputeEFM at line 281, column 5
```

**Comment by axelvonkamp** [comment]
Fixed on CNA side.
