### ISSUE TITLE
Compute EFM via CNA crashes on empty model

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#212]
```
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/efm_dialog.py", line 231, in compute
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 500, in eval
    plot_res=plot_res)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 382, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/oct2py/core.py", line 582, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: Incorrect input
error: called from:
    compute_elmodes at line 114, column 5
    CNAcomputeEFM at line 281, column 5
```

**Comment by axelvonkamp** [comment]
Fixed in branch avk/bugfixes.
