### ISSUE TITLE
Saving MCS crashes CNApy

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#215]
`Traceback (most recent call last):`
`File "C:\Users\phili\cnapy\cnapy\cnapy\gui_elements\mainwindow.py", line 624, in save_modes`
`self.appdata.project.modes.save(filename)`
`AttributeError: 'list' object has no attribute 'save' `

**Comment by sthiele** [comment]
related
```
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/mcs_dialog.py", line 321, in compute
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/mcs_dialog.py", line 487, in compute_legacy
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/centralwidget.py", line 243, in update_mode
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/centralwidget.py", line 252, in update
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/modenavigator.py", line 50, in update
AttributeError: 'list' object has no attribute 'irreversible'
zsh: abort (core dumped)  python cnapy
```

**Comment by sthiele** [comment]
Actually there is no option to save MCS. Saving is only implemented for elementary flux modes.
 @axelvonkamp: I think I would make sense to handle mcs similar to efm. What do you think?

**Comment by VonAlphaBisZulu** [comment]
True. I instinctively picked the "save modes..." button for saving MCS 😅

**Comment by axelvonkamp** [comment]
I think for MCS it is alright to save them just as lists of dictionaries as was done originally with efm.
