### ISSUE TITLE
Flux vector has no attribute irreversible attribute

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#217]
```
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/mcs_dialog.py", line 321, in compute
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/mcs_dialog.py", line 487, in compute_legacy
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/centralwidget.py", line 243, in update_mode
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/centralwidget.py", line 252, in update
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cnapy-0.0.5-py3.7.egg/cnapy/gui_elements/modenavigator.py", line 50, in update
AttributeError: 'list' object has no attribute 'irreversible'
zsh: abort (core dumped)  python cnapy
```

**Comment by sthiele** [comment]
This happened because I used an old .npz file that did not contain the irreversible attribute. Something like this always happens when one tries to open an invalid file. We should have a special error message for that.
