### ISSUE TITLE
Error when creating multiple empty reaction annotations

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#255]
**Describe the bug**
When I create multiple empty reaction annotations, the following traceback is shown in an error window:

Traceback (most recent call last): File "C:\0Applications\CNApy\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 631, in reaction_data_changed self.apply() File "C:\0Applications\CNApy\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 506, in apply key = self.annotation.item(i, 0).text() AttributeError: 'NoneType' object has no attribute 'text' File "C:\0Applications\CNApy\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 631, in reaction_data_changed self.apply() File "C:\0Applications\CNApy\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 506, in apply key = self.annotation.item(i, 0).text() 

**To Reproduce**
1. Open a CNApy model
2. Select a reaction
3. Click "+" under annotations multiple times
4. Click around in the empty annotations

**Expected behavior**
No error or that it's not possible to create multiple empty annotations.

**Please complete the following information:**
 - OS: Windows 10
 - Python version: 3.7

**Comment by sthiele** [comment]
This should be fixed with this commit de1a74fabe391f72d3725ff52ed97b177fc7a29e
