### ISSUE TITLE
Throwback when changing reaction which does not have a reaction map box

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#296]
With the current prerelease:

Traceback (most recent call last): File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\central_widget.py", line 126, in handle_changed_reaction self.update_reaction_on_maps(old_id, reaction.id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\central_widget.py", line 290, in update_reaction_on_maps m.update_reaction(old_reaction_id, new_reaction_id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\map_view.py", line 248, in update_reaction self.delete_box(old_reaction_id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\map_view.py", line 242, in delete_box box = self.reaction_boxes[reaction_id] KeyError: 'R9' File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\central_widget.py", line 126, in handle_changed_reaction self.update_reaction_on_maps(old_id, reaction.id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\central_widget.py", line 290, in update_reaction_on_maps m.update_reaction(old_reaction_id, new_reaction_id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\map_view.py", line 248, in update_reaction self.delete_box(old_reaction_id) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\map_view.py", line 242, in delete_box box = self.reaction_boxes[reaction_id]

**Comment by Paulocracy** [comment]
Addendum: "WARNING:cobra.core.model:Ignoring reaction 'R9' since it already exists." is given before in the console

**Comment by Paulocracy** [comment]
Resolved with #302
