### ISSUE TITLE
Cannot open MCS window

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#297]
Traceback (most recent call last): File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\main_window.py", line 1296, in mcs self.appdata, self.centralWidget()) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\mcs_dialog.py", line 210, in __init__ self.eng.is_cplex_matlab_ready()) AttributeError: 'NoneType' object has no attribute 'is_cplex_matlab_ready' File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\main_window.py", line 1296, in mcs self.appdata, self.centralWidget()) File "C:\GitHub\CNApy_Org\CNApy\cnapy\gui_elements\mcs_dialog.py", line 210, in __init__ self.eng.is_cplex_matlab_ready())

**Comment by Paulocracy** [comment]
Addendum: After several starts of CNApy, this problem somehow does not occur anymore, nevertheless, this error should not occur at all

**Comment by Paulocracy** [comment]
Resolved with #303

**Comment by Paulocracy** [comment]
Under circumstances that I cannot reproduce, a very similar error appears again!
![Error](https://user-images.githubusercontent.com/36934614/134482657-c68afc27-685a-4a47-926c-1099d4f49f13.png)
