### ISSUE TITLE
Error when loading .cna files

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#320]
**System**
CNApy 1.0.3, miniconda3, Ubuntu 21.04

**Traceback excerpt**
 Traceback (most recent call last): File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/site-packages/cobra/core/model.py", line 410, in copy new._solver = deepcopy(self.solver) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/copy.py", line 180, in deepcopy y = _reconstruct(x, memo, *rv) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/copy.py", line 283, in _reconstruct y.__setstate__(state) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/site-

**Comment by sthiele** [comment]
I guess we can close this now. Since it is unlikely that we get further info.
