### ISSUE TITLE
Error on SBML export

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#321]
**System**
CNApy 1.0.3, miniconda3, Ubuntu 21.04

**Traceback excerpt**
Traceback (most recent call last): File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/site-packages/cobra/core/model.py", line 410, in copy new._solver = deepcopy(self.solver) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/copy.py", line 180, in deepcopy y = _reconstruct(x, memo, *rv) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/copy.py", line 283, in _reconstruct y.__setstate__(state) File "/home/dev/miniconda3/envs/cnapy13/lib/python3.7/site-packages/optlang/glpk_interface.py", line

**Comment by axelvonkamp** [comment]
Might be an issue with prune_unused_metabolites as reported in issue #345.
