### ISSUE TITLE
MCS computation with optlang fails in Windows because of error during compression: efmtool4cobra.py

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#341]
After setting up an MCS problem and pressing "Compute MCS", the computation fails with the following error:

```
Running FVA to find blocked reactions... 
1.1410000000032596
Read LP format model from file C:\Users\phili\AppData\Local\Temp\tmp43k00she.lp
Reading time = 0.01 seconds: 509 rows, 1172 columns, 5044 nonzeros
Traceback (most recent call last): 
File "C:\Users\phili\cnapy\lib\site-packages\cnapy\gui_elements\mcs_dialog.py", line 601, in compute_optlang: 
    exclude_boundary_reactions_as_cuts=self.exclude_boundary.isChecked())  
File "C:\Users\phili\cnapy\lib\site-packages\optlang_enumerator\mcs_computation.py", line 307, in compute_mcs:  
    subT = efmtool4cobra.compress_model_sympy(compr_model)
File "C:\Users\phili\cnapy\lib\site-packages\efmtool_link\efmtool4cobra.py", line 113, in compress_model_sympy: 
    n, d = sympyRat2jBigIntegerPair(v)
File "C:\Users\phili\cnapy\lib\site-packages\efmtool_link\efmtool4cobra.py", line 217, in sympyRat2jBigIntegerPair: 
    numer = val.numerator(): TypeError: 'int' object is not callable 
```

**Comment by Paulocracy** [comment]
+1, I can replicate this error

**Comment by axelvonkamp** [comment]
Fixed it in efmtool_link package.
