### ISSUE TITLE
Error on loading MCS window

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#347]
Traceback (most recent call last): File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\gui_elements\main_window.py", line 1421, in mcs self.appdata, self.centralWidget()) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\gui_elements\mcs_dialog.py", line 208, in __init__ self.eng.is_cplex_matlab_ready()) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\CNA_MEngine.py", line 22, in is_cplex_matlab_ready return self.eval('cnan.cplex_interface.matlab;') File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__ _stderr, feval=True).result() File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\futureresult.py", line 67, in result return self.__future.result(timeout) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err) matlab.engine.MatlabExecutionError: Reference to non-existent field 'cplex_interface'. File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\gui_elements\main_window.py", line 1421, in mcs self.appdata, self.centralWidget()) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\gui_elements\mcs_dialog.py", line 208, in __init__ self.eng.is_cplex_matlab_ready()) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\cnapy\CNA_MEngine.py", line 22, in is_cplex_matlab_ready return self.eval('cnan.cplex_interface.matlab;') File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__ _stderr, feval=True).result() File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\futureresult.py", line 67, in result return self.__future.result(timeout) File "C:\Users\mr01222\Anaconda3\envs\cnapy-1.0.5\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)

**Comment by Paulocracy** [comment]
Solved (with a workaround) thanks to #348
