### ISSUE TITLE
TypeError: update_item() missing 1 required positional argument: 'item'  when create new reaction.

### ISSUE THREAD

**Issue by jeromeRlon** [cnapy-org/CNApy#390]
When I create a new reaction, every times i typed in the box of Id or Name or rate min/max, it would reported a error like this: 

Traceback (most recent call last): File "/home/jerome/anaconda3/envs/cnapy-1.0.9/lib/python3.8/site-packages/cnapy/gui_elements/reactions_list.py", line 930, in reaction_data_changed self.apply() File "/home/jerome/anaconda3/envs/cnapy-1.0.9/lib/python3.8/site-packages/cnapy/gui_elements/reactions_list.py", line 734, in apply self.parent.update_item() TypeError: update_item() missing 1 required positional argument: 'item' 
Please report the problem to:
https://github.com/cnapy-org/CNApy/issues

"No solution, the current scenario is infeasible" woeld also be reported in the ipython part.

**Comment by axelvonkamp** [comment]
Thank you for reporting this issue, it will be fixed with the next release (coming very soon).

**Comment by jeromeRlon** [comment]
Thanks for reply. Since that i can not create any reaction works, due to either it reported "No solution, the current scenario is infeasible" or the flux can only be zero. Is this a problem about my operation?

**Comment by axelvonkamp** [comment]
Try version 1.1.1, the bug is fixed there.
You can also try the projects at https://github.com/cnapy-org/CNApy-projects, they should work. They can be downloaded via the CNApy file menu.
