### ISSUE TITLE
EFMTool failure

### ISSUE THREAD

**Issue by dtusso2020** [cnapy-org/CNApy#466]
Hello everyone. I am trying to do a Elementary Flux modes but I got the next error. I am working on windows 
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at ch.javasoft.metabolic.efm.util.ColumnUtil.mergeNumeric(ColumnUtil.java:373)
        at ch.javasoft.metabolic.efm.util.ColumnUtil.mergeNumeric(ColumnUtil.java:364)
        at ch.javasoft.metabolic.efm.model.nullspace.NullspaceDoubleColumnInspectorModifier.mergeNumeric(NullspaceDoubleColumnInspectorModifier.java:106)
        at ch.javasoft.metabolic.efm.model.nullspace.NullspaceDoubleColumnInspectorModifier.mergeNumeric(NullspaceDoubleColumnInspectorModifier.java:1)
        at ch.javasoft.metabolic.efm.column.DoubleColumn.mergeWith(DoubleColumn.java:119)
        at ch.javasoft.metabolic.efm.column.DoubleColumn.mergeWith(DoubleColumn.java:114)
        at ch.javasoft.metabolic.efm.adj.incore.AbstractAdjacencyEnumerator.adjacentPairs(AbstractAdjacencyEnumerator.java:76)
        at ch.javasoft.metabolic.efm.impl.SequentialDoubleDescriptionImpl.iterate(SequentialDoubleDescriptionImpl.java:117)
        at ch.javasoft.metabolic.efm.impl.AbstractDoubleDescriptionImpl.calculateEfms(AbstractDoubleDescriptionImpl.java:163)
        at ch.javasoft.metabolic.efm.impl.AbstractDoubleDescriptionImpl.calculateEfms(AbstractDoubleDescriptionImpl.java:130)
        at ch.javasoft.metabolic.efm.ElementaryFluxModes.calculateCallback(ElementaryFluxModes.java:285)
        at ch.javasoft.metabolic.efm.main.CalculateFluxModes.start(CalculateFluxModes.java:219)
        at ch.javasoft.metabolic.efm.main.CalculateFluxModes.start(CalculateFluxModes.java:143)
        at ch.javasoft.metabolic.efm.main.CalculateFluxModes.main(CalculateFluxModes.java:100)
EFMtool failure`

How to fix it? Thank you so much.

**Comment by axelvonkamp** [comment]
How large is your network? EFM enumeration is usually only possible for smaller networks because of combinatorial explosion.
