### ISSUE TITLE
error running CNApy

### ISSUE THREAD

**Issue by Laminsecin** [cnapy-org/CNApy#470]
I installed CNApy as conda package. after the installation was done I activated cnapy-1.1.6 and when I wanted to run cnapy I encounter the following error:
URLs with no authority component cannot have a path starting with '//'.
can somebody help me?
I also want to know if it is possible to install CNApy on pycharm and how.

**Comment by axelvonkamp** [comment]
The bug is an issue from cobrapy, you need to upgrade to version 0.26.3.

**Comment by Laminsecin** [comment]
> The bug is an issue from cobrapy, you need to upgrade to version 0.26.3.

Thanks for your response, but unfortunately after upgrading cobrapy the error appears again and the CNApy 1.1.6 suddenly closes.

**Comment by axelvonkamp** [comment]
Can you copy & paste the complete stack trace here? This may help to figure out what is going on.

**Comment by Laminsecin** [comment]
Yes, sure. this is my version of cobra:
(base) C:\Users\asus>conda list
# packages in environment at C:\Users\asus\miniconda3:
#
# Name                    Version                   Build  Channel
cobra                     0.26.3             pyhd8ed1ab_0    conda-forge
=========================================
and this is the error I get running cnapy:
(base) C:\Users\asus>conda activate cnapy-1.1.6

(cnapy-1.1.6) C:\Users\asus>cnapy
Traceback (most recent call last):
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\Scripts\cnapy-script.py", line 6, in <module>
    from cnapy.__main__ import main_cnapy
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\__main__.py", line 31, in <module>
    from cnapy.application import Application
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\application.py", line 25, in <module>
    import cobra
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\__init__.py", line 17, in <module>
    from cobra import io
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\__init__.py", line 9, in <module>
    from cobra.io.web import AbstractModelRepository, BiGGModels, BioModels, load_model
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\web\__init__.py", line 7, in <module>
    from .load import load_model
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\web\load.py", line 31, in <module>
    Cobrapy(),
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\web\cobrapy_repository.py", line 36, in __init__
    super().__init__(url="file:////", **kwargs)
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\cobra\io\web\abstract_model_repository.py", line 55, in __init__
    self._url = httpx.URL(url=url)
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\httpx\_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\httpx\_urlparse.py", line 252, in urlparse
    validate_path(path, has_scheme=has_scheme, has_authority=has_authority)
  File "C:\Users\asus\miniconda3\envs\cnapy-1.1.6\lib\site-packages\httpx\_urlparse.py", line 367, in validate_path
    raise InvalidURL(
httpx.InvalidURL: URLs with no authority component cannot have a path starting with '//'

**Comment by axelvonkamp** [comment]
The updated cobra package appears to be in the (base) environment, but is it also updated in the (cnapy-1.1.6) environment?
