### ISSUE TITLE
Error on startup with pre release 1.1.7

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#472]
Following the install instruction I get the following error.
```sh
❯  conda activate cnapy-1.1.7
❯ cnapy
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/bin/cnapy", line 6, in <module>
    from cnapy.__main__ import main_cnapy
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/cnapy/__main__.py", line 31, in <module>
    from cnapy.application import Application
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/cnapy/application.py", line 42, in <module>
    from cnapy.gui_elements.main_window import MainWindow
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/cnapy/gui_elements/main_window.py", line 10, in <module>
    from cnapy.core import model_optimization_with_exceptions
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/cnapy/core.py", line 15, in <module>
    import efmtool_link.efmtool4cobra as efmtool4cobra
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/efmtool_link/efmtool4cobra.py", line 1, in <module>
    import efmtool_link.efmtool_intern as efmtool_intern
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/efmtool_link/efmtool_intern.py", line 9, in <module>
    jpype.startJVM()
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/jpype/_core.py", line 184, in startJVM
    jvmpath = getDefaultJVMPath()
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/jpype/_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "/home/sthiele/miniconda3/envs/cnapy-1.1.7/lib/python3.8/site-packages/jpype/_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try setting up the JAVA_HOME environment variable properly.
```

**Comment by sthiele** [comment]
Maybe it has something to do with openjdk which is now on version  openjdk=8.0.332=h166bdaf_0 for me?

**Comment by sthiele** [comment]
> What is the jpype1 version of your environment?

  - jpype1=1.4.1=py38h43d8883_1

**Comment by axelvonkamp** [comment]
Can you try an older version of jpype1? I still have got 1.2.1. Strangely though, the PR checks did not show this issue.

**Comment by sthiele** [comment]
I downgraded to `jpype1=1.2.1=py38h1fd1430_0` and have the same issue.

>  Strangely though, the PR checks did not show this issue.

Might be because I'm not on an ubuntu machine.

**Comment by axelvonkamp** [comment]
Can you try to replace the line 678 in reactions_list.py with
```
self.grp_test_model.add_reactions([reaction])
```
add_reaction is deprecated but should actually still work.

**Comment by sthiele** [comment]
Oh yeah, some other things I noted. 
- The scenario name is in an unfortunate position I think I can click on it but nothing happens.
- Idea: Maybe replace the icon for scenario open with the name of the scenario
- The other toolbar buttons (save/as scenario) if they are disabled should be greyed out
- How do I know that the scenario has been changed/unsaved? I think there should be some indication if the current scenario is not the same as the one that is on the label.
