### ISSUE TITLE
Problems Installing Cnapy

### ISSUE THREAD

**Issue by Ivano2021** [cnapy-org/CNApy#490]
Traceback (most recent call last): File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\Scripts\cnapy-script.py", line 10, in sys.exit(main_cnapy()) File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\lib\site-packages\cnapy\__main__.py", line 34, in main_cnapy Application() File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\lib\site-packages\cnapy\application.py", line 76, in __init__ self.window = MainWindow(self.appdata) File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\lib\site-packages\cnapy\gui_elements\main_window.py", line 68, in __init__ self.central_widget = CentralWidget(self) File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\lib\site-packages\cnapy\gui_elements\central_widget.py", line 72, in __init__ self.reaction_list = ReactionList(self) File "D:\Usuarios\iprivitera\.conda\envs\cnapy-1.1.8\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 128, in __init__ for r in self.appdata.project.cobra_py_model.reactions: AttributeError: 'ProjectData' object has no attribute 'cobra_py_model' 

 Hello!
I tried to install Cnapy in my job computer, wich has Windows, I used Anaconda to download the cnapy packages with the commands put in the cnapy installation page, but when I thaught that was alla ok when i tried to run the program appears the message above.

**Comment by Paulocracy** [comment]
Hello! We don't directly recognize the problem :3 But it appears that you tried to install an older version (1.1.8) instead of the most recent one (1.1.9), so that it woud help us if you would try to install version 1.1.9 and see if the same error occurs?

**Comment by uliebal** [comment]
I also have a similar error with the newest version 1.1.9. I am trying an installation on Win10 and used both the  "INSTALL_CNAPY.bat" and the conda install procedure. My error message is:

Traceback (most recent call last): File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\Scripts\cnapy-script.py", line 10, in sys.exit(main_cnapy()) File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\lib\site-packages\cnapy\__main__.py", line 34, in main_cnapy Application() File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\lib\site-packages\cnapy\application.py", line 76, in __init__ self.window = MainWindow(self.appdata) File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\lib\site-packages\cnapy\gui_elements\main_window.py", line 68, in __init__ self.central_widget = CentralWidget(self) File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\lib\site-packages\cnapy\gui_elements\central_widget.py", line 72, in __init__ self.reaction_list = ReactionList(self) File "C:\Users\liebalu\.conda\envs\cnapy-1.1.9\lib\site-packages\cnapy\gui_elements\reactions_list.py", line 137, in __init__ for r in self.appdata.project.cobra_py_model.reactions: AttributeError: 'ProjectData' object has no attribute 'cobra_py_model'

**Comment by Paulocracy** [comment]
Thank you @uliebal for the additional report! Finally, we also had a colleague with the same error xD, which can be solved through a different Gurobi error handling routine. Therefore, I'd like to ask if you (and @Ivano2021 :-) also get Gurobi errors before this final error message?

**Comment by Ivano2021** [comment]
Hello! Sorry for the delay! Clearly I saw that Cnapy works better in MacOS, in Windows is different, even in my MacOS I had to change the solver, instead of Gurobi, I installed GLPK. Beacuse I had the option once I was in the app,  but in Windows was impossible (I work with Windows in my job, but I have a Macbook. Maybe If I install GLPK as a solver for Cnapy can work, but I don´t know how to do it. Thanks.

**Comment by Paulocracy** [comment]
@Ivano2021 There's no problem with the delay :-) I'm glad to hear that it's connected to the Gurobi issue our colleague had, that's what the new commit (and the next release) will solve, so that CNApy should also run for you under Windows :D

**Comment by uliebal** [comment]
I also had the Gurobi error message, so I am looking forward to the next release.

**Comment by Paulocracy** [comment]
@uliebal @Ivano2021  Our newest release 1.1.10 is now ready, including a fix which should solve this issue:
https://github.com/cnapy-org/CNApy/releases/tag/v1.1.10

**Comment by Paulocracy** [comment]
As the problem does not seem to persist anymore, I'll close this issue. But if there are any new problems (or even the same D:), feel free to open a new issue :-)
