### ISSUE TITLE
Error when saving Escher SVG as CNApy-style map

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#520]
Traceback (most recent call last): File "/scratch/GitHub/CNApy/cnapy/gui_elements/main_window.py", line 1423, in wait_for_retrieval self.continue_save_project() File "/scratch/GitHub/CNApy/cnapy/gui_elements/main_window.py", line 1472, in continue_save_project zip_obj.write(name, arcname=m) File "/scratch/mambaforge/envs/cnapy-dev-38/lib/python3.8/zipfile.py", line 1741, in write zinfo = ZipInfo.from_file(filename, arcname, File "/scratch/mambaforge/envs/cnapy-dev-38/lib/python3.8/zipfile.py", line 523, in from_file st = os.stat(filename) FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkd3a8lix/map1.svg'

**Comment by Paulocracy** [comment]
Fixed thanks to @axelvonkamp :D
